# Generated by Django 4.2.2 on 2023-07-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climbs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="problems", to="climbs.tag"
            ),
        ),
    ]
