# Generated by Django 4.2.2 on 2023-07-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("climbs", "0002_alter_problem_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopoImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/topo_images/")),
                (
                    "climbable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="climbs.climbable",
                    ),
                ),
            ],
        ),
    ]
