# Generated by Django 4.2.2 on 2023-08-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climbs", "0003_topoimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Climbable",
            new_name="Location",
        ),
        migrations.RenameField(
            model_name="problem",
            old_name="climbable",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="topoimage",
            old_name="climbable",
            new_name="location",
        ),
        migrations.AlterField(
            model_name="topoimage",
            name="image",
            field=models.ImageField(upload_to="topo_images/"),
        ),
    ]
