# Generated by Django 4.2.2 on 2023-08-07 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climbs", "0004_rename_climbable_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="location",
            new_name="position",
        ),
    ]
