# Generated by Django 4.2.2 on 2023-08-08 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climbs", "0005_rename_location_location_position"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TopoImage",
            new_name="LocationImage",
        ),
    ]
