# Generated by Django 4.2.2 on 2023-08-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climbs", "0006_rename_topoimage_locationimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationimage",
            name="image_height",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locationimage",
            name="image_width",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="locationimage",
            name="image",
            field=models.ImageField(
                height_field="image_height",
                upload_to="location_images/",
                width_field="image_width",
            ),
        ),
    ]
