# Generated by Django 4.2.2 on 2023-08-22 13:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "climbs",
            "0007_locationimage_image_height_locationimage_image_width_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                (
                    "location_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="climbs.locationimage",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="climbs.problem"
                    ),
                ),
            ],
        ),
    ]
