# Generated by Django 4.2.2 on 2023-08-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climbs", "0008_line"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="line",
            constraint=models.UniqueConstraint(
                fields=("problem", "location_image"),
                name="problem and location_image must be unique together",
            ),
        ),
    ]
