# Generated by Django 4.2.2 on 2023-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_climbable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="climbable",
            name="type",
            field=models.CharField(
                choices=[("BL", "block"), ("WA", "wall")], default="BL", max_length=2
            ),
        ),
    ]
