# Generated by Django 4.2.2 on 2023-07-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_tag_alter_climbable_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                ("grade", models.CharField(max_length=4)),
                (
                    "climbable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.climbable"
                    ),
                ),
                ("tags", models.ManyToManyField(to="core.tag")),
            ],
        ),
    ]
