# Generated by Django 4.2.2 on 2023-07-18 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("climbs", "0002_alter_problem_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ascent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "given_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Horrible"),
                            (1, "Ok"),
                            (2, "Good"),
                            (3, "Great"),
                            (4, "Amazing"),
                            (5, "Perfect"),
                        ],
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="", max_length=1000)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="climbs.problem"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
