# Generated by Django 4.2.2 on 2023-07-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ascent",
            constraint=models.UniqueConstraint(
                fields=("user", "problem"),
                name="user and problem must be unique together",
            ),
        ),
    ]
